version: '2'

services:
  oceanshar_app:
    container_name: oceanshare
    build:
      context: .
      image: node:latesté
    volumes:
      - '.:/usr/src/app'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development